---
- name: Apply psp
  k8s:
    state: present
    definition: "{{ lookup('file', item) | from_yaml_all | list }}"
  with_fileglob:
    - "{{ role_path }}/files/psp/*.yaml"

- name: Add metrics-service (Used by kubctl top node/pod and k9s)
  k8s:
    state: present
    definition: "{{ item }}"
  loop: "{{ lookup('file', '{{ role_path }}/files/metrics-server.yaml') | from_yaml_all | list }}"

- name: Add nginx-ingress service
  k8s:
    definition: "{{ item }}"
    state: present
  loop: "{{ lookup('file', '{{ role_path }}/files/nginx-ingress.yaml') | from_yaml_all | list }}"

- name: Add local storage
  k8s:
    definition: "{{ item }}"
    state: present
  loop: "{{ lookup('file', '{{ role_path }}/files/local-path-storage.yaml') | from_yaml_all | list }}"

#- name: Add cert-manager
#  k8s:
#    definition: "{{ item }}"
#    state: present
#  loop: '{{ lookup("url", "https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.yaml", split_lines=False) | from_yaml_all | list }}'
#
#- name: Add cert-manager ACME client
#  k8s:
#    definition: "{{ item }}"
#    state: present
#  loop: "{{ lookup('template', '{{ role_path }}/files/cert-manager-acme.yaml') | from_yaml_all | list }}"
#  register: result
#  retries: 5
#  delay: 2
#  until: result is not failed
