---
- name: Add metrics-service (Used by kubctl top node/pod and k9s)
  k8s:
    state: present
    definition: "{{ item }}"
  loop: "{{ lookup('template', '{{ role_path }}/files/metrics-server.yml') | from_yaml_all | list }}"
