---
- name: Check if cluster exists
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: result

- name: Pull kubeadm images
  shell: kubeadm config images pull
  when: not result.stat.exists

- name: Initialize cluster slave
  shell: >
    kubeadm join \
    --token {{ kubeadm_token }} \
    --discovery-token-unsafe-skip-ca-verification \
    k8s.espinoza.dev:6443
  when: not result.stat.exists
