---
- name: Copy kubernetes repo configuration
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  with_fileglob: "*"
  register: copy_data

- name: Set SELinux in permissive mode
  shell: ( setenforce 0 || true ) && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  when: copy_data.changed

- name: Install kubelet
  yum:
    name: "{{ packages }}"
    state: present
    disable_excludes: kubernetes
  vars:
    packages:
    - kubelet-1.18.6-0
    - kubeadm-1.18.6-0
    - kubectl-1.18.6-0
    - iscsi-initiator-utils # LongHorn
  when: copy_data.changed

- name: Enable kubelet
  shell: systemctl enable --now kubelet
  when: copy_data.changed

- name: Setup network configuration
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  with_fileglob: "*"
  register: copy_data

- name: Make sure br_netfilter is loaded
  shell: modprobe br_netfilter
  when: copy_data.changed

- name: Restart kubelet
  shell: systemctl restart kubelet
  when: copy_data.changed
