---
- name: Check if cluster exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: result

- name: Pull kubeadm images
  shell: kubeadm config images pull
  when: not result.stat.exists

- name: Initialize cluster
  shell: >
    kubeadm init \
    --token {{ kubeadm_token }} \
    --token-ttl 10m \
    --pod-network-cidr 10.248.0.0/16
    #--control-plane-endpoint {{ groups['master'][0] }} \ # Needed for HA
  when: not result.stat.exists

- name: Wait for cluster
  wait_for:
    timeout: 60
    port: 6443
  when: not result.stat.exists

- name: Apply Calico network
  shell: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
  when: not result.stat.exists

- name: Allow the schedule of nodes in master
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  when: not result.stat.exists

- name: Copy admin.conf
  shell: >
    sudo -u ec2-user mkdir -p /home/ec2-user/.kube && \
    cp -i /etc/kubernetes/admin.conf /home/ec2-user/.kube/config && \
    chown ec2-user:ec2-user /home/ec2-user/.kube/config
  when: not result.stat.exists

