---
- name: Create namespace
  k8s:
    state: present
    definition: "{{ lookup('file', 'namespace.yaml') }}"

- name: Add encryption master key
  k8s:
    state: present
    definition: "{{ lookup('file', 'masterk.key') }}"

- name: Install sealed-secrets
  k8s:
    state: present
    definition: "{{ lookup('file', 'sealed-secrets.yaml') }}"
