---
- name: Create namespace
  k8s:
    state: present
    definition: "{{ lookup('file', 'namespace.yaml') }}"

- name: Add encryption master key
  k8s:
    state: present
    definition: "{{ lookup('file', 'masterk.key') }}"

- name: Create sealed-secrets
  shell: >
    export KUBECONFIG={{ playbook_dir }}/fdns.conf && \
    cd {{ role_path }}/files && \
    helmfile sync
  delegate_to: localhost
