---
# Install docker for kubernetes, based on https://kubernetes.io/docs/setup/production-environment/container-runtimes/
- name: Check if docker is installed
  shell: command -v docker
  register: docker_check
  ignore_errors: yes
  failed_when: False
  changed_when: False

- set_fact:
    docker_installed: "{{ docker_check.rc == 0 }}"

- name: Update yum packages
  shell: yum update -y
  when: not docker_installed

- name: Install docker
  shell: amazon-linux-extras install docker
  when: not docker_installed

- name: Create config folder
  file:
    path: /etc/docker/
    state: directory

- name: Copy docker config to target
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  with_fileglob: "*"
  register: copy_data

- name: Create systemd docker folder
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Enable the docker daemon
  shell: systemctl daemon-reload && systemctl enable docker
  when: not docker_installed

- name: Start the docker daemon
  shell: systemctl restart docker
  when: not docker_installed

- name: Add user to docker group
  user:
    name: ec2-user
    groups: 'docker'
    append: 'yes'
  when: not docker_installed

- name: Reset ssh to load new docker groups
  meta: reset_connection
  when: not docker_installed
