---
- name: Setup cloudflare master ingress dns
  cloudflare_dns:
    zone: espinoza.dev
    record: '{{ item }}'
    type: A
    proxied: yes
    solo: yes
    value: '{{ ec2_ip_address }}'
    account_email: '{{ cloudflare_api_user }}'
    account_api_token: '{{ cloudflare_api_token }}'
  loop:
    - edx.k8s
    - studio.edx.k8s
    - preview.edx.k8s
    - s3.edx.k8s

- name: Setup main k8s entrypoint
  cloudflare_dns:
    zone: espinoza.dev
    record: k8s
    type: A
    proxied: no
    solo: yes
    value: '{{ ec2_ip_address }}'
    account_email: '{{ cloudflare_api_user }}'
    account_api_token: '{{ cloudflare_api_token }}'
