---
- name: Copy wireguard repo configuration
  copy:
    src: wireguard.repo
    dest: /etc/yum.repos.d/wireguard.repo
  with_fileglob: "*"
  register: copy_data

- name: Install wireguard
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - wireguard-dkms
    - wireguard-tools
    - iptables-services
  when: copy_data.changed

- name: Update kernel
  shell: yum update -y
  when: copy_data.changed

- name: Reboot the machine to load new kernel
  reboot:
  when: copy_data.changed

- name: Reinstall wireguard with new kernel
  shell: dkms autoinstall

#- name: load wireguard
#  modprobe:
#    name: wireguard
#    state: present
#  when: copy_data.changed

- name: Allow IP Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  when: copy_data.changed

- name: Store forwarding config
  copy:
    src: wg.conf
    dest: /etc/sysctl.d/wg.conf
  with_fileglob: "*"
  when: copy_data.changed

- name: Create wireguard config folder
  file:
    path: /etc/wireguard/
    state: directory
  when: copy_data.changed

- name: Render wireguard
  template:
    src: wg0.conf
    dest: /etc/wireguard/wg0.conf
    mode: '0600'
  register: template_data

- name: Enable wireguard
  shell: systemctl enable wg-quick@wg0.service && systemctl start wg-quick@wg0.service
  when: copy_data.changed

- name: Reload wireguard
  shell: systemctl restart wg-quick@wg0.service
  when: template_data.changed and not copy_data.changed
